title: Journey_of_coding
author: Pradnya R K
email: pradnyarkanale@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is all about:-
    -how a novice coder ascends learning right from the basics facing challenges 
    -solutions to the problems faced during the same (for fellow novice coders ;) ) 
    -relatable discussions at the intersection of programming languages, softwares for different purposes, web-dev AND "big buzzwords" !
theme: minima
# social links
twitter_username: pradnyarkanale # DO NOT include the @ character, or else the build will fail!
github_username:  pradnyarkanale # DO NOT include the @ character, or else the build will fail!
instagram_username: pradnyarkanale
show_excerpts: true # set to false to remove excerpts on the homepage
